import Head from "next/head";
import { useState } from "react";
import Footer from "../components/Footer";
import Header from "../components/Header";
import Info from "../components/Info";
import Links from "../components/Links";
import SearchBar from "../components/SearchBar";
import db from "../utils/firebase";

export default function Home({ data }) {
  const [filteredSearch, setFilteredSearch] = useState(null);
  const handleChange = (e) => {
    const search = e.target.value;
    if (!search) {
      setFilteredSearch(null);
      return;
    }
    setFilteredSearch(
      data.filter((doc) =>
        doc.keywords.toLowerCase().includes(search.toLowerCase())
      )
    );
  };

  return (
    <div className="flex flex-col min-h-screen w-full">
      <Head>
        <title>Hackerman Links</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <Info />

      <SearchBar handleChange={handleChange} />
      <div className="flex-grow">
        <Links filteredSearch={filteredSearch} data={data} />
      </div>
      <Footer />
    </div>
  );
}

export async function getServerSideProps(context) {
  const linksData = await db.collection("links").get();

  const data = linksData.docs.map((doc) => ({
    id: doc.id,
    ...doc.data(),
    timestamp: null,
  }));
  return {
    props: { data: data },
  };
}
