import Head from "next/head";
import { useState } from "react";
import Header from "../components/Header";
import LinkCard from "../components/LinkCard";
import db from "../utils/firebase";

export default function Home({ data }) {
  const [filteredSearch, setFilteredSearch] = useState(null);
  const handleChange = (e) => {
    const search = e.target.value;
    if (!search) {
      setFilteredSearch(null);
      return;
    }
    setFilteredSearch(
      data.filter((doc) =>
        doc.keywords.toLowerCase().includes(search.toLowerCase())
      )
    );
  };

  return (
    <div className="">
      <Head>
        <title>Hackerman Links</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header handleChange={handleChange} />

      <div className="flex w-screen flex-wrap justify-center">
        {filteredSearch
          ? filteredSearch?.map((doc) => (
              <LinkCard
                key={doc.id}
                name={doc.name}
                path={doc.path}
                to={doc.to}
              />
            ))
          : data?.map((doc) => (
              <LinkCard
                key={doc.id}
                name={doc.name}
                path={doc.path}
                to={doc.to}
              />
            ))}
      </div>
    </div>
  );
}

export async function getServerSideProps(context) {
  const linksData = await db.collection("links").get();

  const user = docs.length === 1 ? username : null;
  const data = linksData.docs.map((doc) => ({
    id: doc.id,
    ...doc.data(),
    timestamp: null,
  }));
  return {
    props: { data: data },
  };
}
